# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * SUN"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github_metrics.svg
          user: JonathanBonnaud
          template: classic
          base: header  #, repositories
          config_display: large
          # Languages plugin
          plugin_languages: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_skipped: JonathanBonnaud/jonathanbonnaud.github.io
#           plugin_languages_indepth: true
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 4
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
          # Achievements plugin
          plugin_achievements: yes
          plugin_achievements_threshold: B       # Display achievements with rank B or higher
          plugin_achievements_secrets: no       # Display unlocked secrets achievements
          plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets params
          plugin_achievements_display: detailed 
