# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * SUN"}]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Update metrics.svg
        uses: lowlighter/metrics@latest
        with:
          # Common config
          user: JonathanBonnaud
          token: ${{ secrets.METRICS_TOKEN }}
          
          template: classic
          filename: github_metrics.svg
          config_display: large
          base: header  #, repositories
          base_indepth: yes
          config_order: base.header, languages, notable, achievements
          
          # Plugin languages
          plugin_languages: yes  # Show language bar
          plugin_languages_sections: most-used, recently-used
          plugin_languages_categories: programming, markup, prose #, data  # All categories
          plugin_languages_details: lines, bytes-size, percentage  # Show percentages, with 2 decimals of precision
          plugin_languages_limit: 8  # Max
          plugin_languages_threshold: 0%  # Don't filter
          plugin_languages_skipped: JonathanBonnaud/jonathanbonnaud.github.io
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
#           plugin_languages_indepth: yes
          
          # Plugin achievements
#           plugin_achievements: true  # Show achievements
#           plugin_achievements_threshold: C  # Show all unlocked achievements
#           plugin_achievements_secrets: true  # Include secret achievements
#           plugin_achievements_limit: 0  # All that can fit
#           plugin_achievements_display: compact  # Compact layout
        
          plugin_notable: yes
