# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * SUN"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics_left.svg
          user: JonathanBonnaud
          template: classic
          base: header  #, repositories
          plugin_languages: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 5
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
      - name: Contributors with contributions count
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.contributors.contributions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          repo: metrics
          plugin_contributors: yes
          plugin_contributors_contributions: yes
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics_right.svg
          user: JonathanBonnaud
          template: classic
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
